In [1]:
import numpy as np
import torch 

In [28]:
a = np.array([[1,2],[1,2]])
a

array([[1, 2],
       [1, 2]])

In [29]:
x = np.array([-1,-1])

In [30]:
np.matmul(x,a)

array([-2, -4])

In [50]:
p1 = np.array(np.matmul(x,a[:,0])).reshape(-1)
p2 = np.array(np.matmul(x,a[:,1])).reshape(-1)

array([-2, -4])

In [52]:
p1 = np.array(np.matmul(x[0].reshape(-1),a[0,:])).reshape(-1)
p2 = np.array(np.matmul(x[1],a[1,:])).reshape(-1)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [15]:
np.concatenate((p1,p2), axis=0)

array([[-1, -2],
       [-1, -2]])

In [16]:
p1 = x[0] * a[:,0]
p2 = x[1] * a[:,1]

In [17]:
p1+p2

array([-3, -3])

In [12]:
mask = torch.full((5,5,),float("-inf"))

In [13]:
mask

tensor([[-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf]])

In [18]:
mask = torch.triu(mask, diagonal=1)

In [19]:
tmp = torch.zeros(5,7)

In [20]:
tmp

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [25]:
a =torch.hstack([tmp,mask])
b= torch.cat((tmp,mask),dim=1)
print(a,b,sep='\n')
torch.equal(a,b)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


True